### ISSUE TITLE
Refuses to build

### ISSUE THREAD

**Issue by earino** [njtierney/visdat#30]
When building visdat I get the following error:
   
    ** preparing package for lazy loading
    Error in as_function(.f, ...) : object 'compare_print' not found
    Error : unable to load R code in package ‘visdat’
    ERROR: lazy loading failed for package ‘visdat’
    * removing ‘/usr/local/lib/R/site-library/visdat’
    Error: Command failed (1)

I believe that "compare_print" no longer exists?

**Comment by njtierney** [comment]
Hey mate,

Thanks for the message,

This prompted me to get `vis_compare` working and do some other fixes, so it should install now - devtools::check() doesn't fail for me. 

That said...my travis build is still failing.

Let me know if the current build installs for you?

**Comment by njtierney** [comment]
OK so it builds on both travis and appveyor now, so it should work on your machine. Let me know if it does.

**Comment by earino** [comment]
Works and installs perfectly :) Thank you!

**Comment by njtierney** [comment]
Wonderful, glad to hear!

**Comment by earino** [comment]
I'd like to add, thank you for building a great package! I use it to visualize data frames quite often. Much appreciated.

**Comment by njtierney** [comment]
No worries, super happy to hear that it is useful for you!
