### ISSUE TITLE
Missing Data not listed in legend

### ISSUE THREAD

**Issue by njtierney** [njtierney/visdat#5]
When running the example2 through `vis_dat`, the grey bars indicate missing values, but these are currently not listed as missing values in the legend.

**Comment by tierneyn** [comment]
I need to make sure that missing data has the same colour. At this stage, simply assigning missing data as it's own class means it's colour will change.

**Comment by njtierney** [comment]
Looks like this is now included in ggplot 2.2.0 for free, sweet!

``` r
visdat::vis_dat(airquality)
```

![](http://i.imgur.com/iaUW5kO.png)

``` r
visdat::vis_miss(airquality)
```

![](http://i.imgur.com/t7P48LA.png)
