### ISSUE TITLE
Error while using vis_dat with diamonds dataset

### ISSUE THREAD

**Issue by nitingupta2** [njtierney/visdat#75]
Here is the error I get when I use vis_dat with diamonds dataset:

> visdat::vis_dat(diamonds)
Error in mutate_impl(.data, dots) : 
  Evaluation error: argument must be coercible to non-negative integer.
In addition: Warning message:
In seq_len(nrow(x)) : first element used of 'length.out' argument

**Comment by njtierney** [comment]
Thank you for filing this issue!

Just confirming that I get the same error:

``` r
visdat::vis_dat(ggplot2::diamonds)
#> Warning in seq_len(nrow(x)): first element used of 'length.out' argument
#> Error in mutate_impl(.data, dots): Evaluation error: argument must be coercible to non-negative integer.
```

Created on 2018-04-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
